name = "CLOUDFLARE_WORKER_NAME"
main = "src/index.ts"
compatibility_date = "2024-12-27"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "CLOUDFLARE_DATABASE_NAME"
database_id = "CLOUDFLARE_DATABASE_ID"
migrations_dir = "drizzle"
